apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-postgres-pvc
  labels:
    name: my-postgres-pvc

spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Mi