apiVersion: v1
kind: PersistentVolume

metadata:
  name: pv-local
  labels:
    name: pv-local

spec:
  storageClassName: manual
  capacity:
    storage: 50Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: '/run/desktop/mnt/host/c/Users/igorp/k8s/pv'