version: '3'

services:
  backend:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./backend
    environment:
      - PGPORT=5000
    depends_on:
      - redis
    volumes:
      - /app/node_modules
      - ./backend:/app 
    # ports:
    #   - '5000:5000'

  redis:
    restart: always
    image: 'redis:alpine'

  frontend:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./frontend
    depends_on:
      - backend
    environment:
      - CHOKIDAR_USEPOLLING="true"
    # ports:
    #   - '3000:3000'

  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./mynginx
    ports:
      - '9090:80'
