apiVersion: v1
kind: Pod
metadata:
  name: lab1zad2

spec:
  containers:
    - name: my-nginx
      image: nginx:alpine
      lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "curl localhost:80"]

