apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
  labels:
    name: mongo-pvc
    
spec:
  storageClassName: manual
  resources:
    requests:
      storage: 80Mi
  accessModes:
    - ReadWriteOnce
