apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-local
  labels:
    name: pv-local

spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: '/run/desktop/mnt/host/c/Users/igorp/k8s/projekt/pv'
