apiVersion: v1
kind: Pod
metadata:
  name: lab1zad4
  labels:
    name: lab1zad4
spec:
  containers:
  - name: my-react
    image: ipustovoy/technologie-chmurowe:react-pod
    imagePullPolicy: Always
    ports:
      - containerPort: 3000
  restartPolicy: OnFailure

---

apiVersion: v1
kind: Service
metadata:
  name: lab1zad4-service
spec:
  selector:
    name: lab1zad4
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30080
  type: NodePort