version: '3'

services:
  api:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./backend
    environment:
      - PGPORT=5000
    ports:
      - '5000:5000'
    volumes:
      - /app/node_modules
      - ./backend:/app 

  redis:
    restart: always
    image: 'redis:alpine'