version: '3'

services:
  api:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./backend
    environment:
      - PGPORT=5000
    ports:
      - '5000:5000'

  redis:
    restart: always
    image: 'redis:alpine'