apiVersion: apps/v1
kind: Deployment

metadata:
  name: lab10zad1
  labels:
    name: lab10zad1

spec:
  template:
    metadata:
      name: my-postgres-pod
      labels:
        name: lab10zad1

    spec: 
      containers:
        - name: my-postgres-container
          image: postgres:alpine
          env: 
            - name: POSTGRES_PASSWORD
              value: "postgres"
            - name: POSTGRES_USER
              value: "postgres"
           
  replicas: 2
  selector: 
    matchLabels:
      name: lab10zad1