apiVersion: v1
kind: Pod
metadata:
  name: lab1zad1
  labels:
    app: first-pod
  
spec:
 containers:
 - name: my-nginx
   image: nginx:alpine

---

apiVersion: v1
kind: Service
metadata:
  name: lab1zad3

spec:
  selector:
    app: first-pod
  ports:
    - name: labzad1
      protocol: TCP
      port: 30080
      nodePort: 30080
      targetPort: 80
  type: NodePort